//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinModel.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FuncOper> FuncOper { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<PageElement> PageElement { get; set; }
        public DbSet<Paper> Paper { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<PermMenu> PermMenu { get; set; }
        public DbSet<PermOperate> PermOperate { get; set; }
        public DbSet<PermPageElement> PermPageElement { get; set; }
        public DbSet<PermPaper> PermPaper { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RolePerm> RolePerm { get; set; }
        public DbSet<SysUser> SysUser { get; set; }
        public DbSet<UserGroup> UserGroup { get; set; }
        public DbSet<UserGroupRelate> UserGroupRelate { get; set; }
        public DbSet<UserGroupRole> UserGroupRole { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
    }
}
