//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXinModel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public int SysUserID { get; set; }
        public string LoginName { get; set; }
        public string Passwd { get; set; }
        public string TrueName { get; set; }
        public string Tel { get; set; }
        public string Gender { get; set; }
        public string AllowIP { get; set; }
        public string IsValidateIP { get; set; }
        public string HomePage { get; set; }
        public string Sts { get; set; }
        public int RoleID { get; set; }
        public byte[] RegTime { get; set; }
        public string QQ { get; set; }
        public int DisFlag { get; set; }
    }
}
